M48
; DRILL file {KiCad 8.0.5} date 2024-11-03T20:33:19+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-03T20:33:19+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0827
%
G90
G05
T1
X4.193Y-2.06
X4.193Y-2.89
X5.667Y-2.06
X5.667Y-2.89
M30
