M48
; DRILL file {KiCad 8.0.5} date 2024-11-03T22:21:11+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-11-03T22:21:11+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
%
G90
G05
T1
X4.2Y-2.8
X4.3Y-2.1
X4.4Y-2.3
X4.4Y-2.8
X4.7Y-2.8
X5.1Y-2.8
X5.4Y-2.8
X5.6Y-2.1
X5.6Y-2.8
M30
